# Change these first
owner: ersinesen # Your GitHub organization or username, where this repository lives
repo: myupptime # The name of this repository

sites:
  - name: Word Duel
    url: https://wordle-duel.web.app/
  - name: Word Duel Backend
    url: https://Wordle-Duel-Backend.ersinesen.repl.co
  - name: Word Duel Türkçe
    url: https://wordle-duello-56e98.web.app/
  - name: Word Duel Türkçe Backend
    url: https://Wordle-Duello-Backend.ersinesen.repl.co
  - name: Mazer
    url: https://mazer.ersinesen.repl.co
  - name: Home Page
    url: https://ersinesen.appspot.com/
  - name: Esenbil
    url: https://www.esenbil.com/
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: /myupptime
  baseUrl: /myupptime
  name: myupptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/ersinesen/myupptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
